[[redirects]]
  from = "/api/*"
  to = "https://foodie-kb4r.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://zestoria.netlify.app", Access-Control-Allow-Credentials = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
